 version: '1.0'

services:
  backend:
    image: your-dockerhub-username/backend
    build:
      context: ./backend
    ports:
      - "3001:3000"
    env_file:
      - ./backend/.env

  frontend:
    image: your-dockerhub-username/frontend
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env