version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3001:3000"
    environment:
      - FINANCIAL_DATASETS_API_KEY=${FINANCIAL_DATASETS_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - LANGGRAPH_API_URL=${LANGGRAPH_API_URL}
      - NEXT_PUBLIC_LANGGRAPH_ASSISTANT_ID=${NEXT_PUBLIC_LANGGRAPH_ASSISTANT_ID}